### ISSUE TITLE
[Task]: Frontend feature flag test errors

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1378]
### Summary

Getting the following:

```
Summary of all failing tests
 FAIL  tests/pages/dev/feature-flags.test.tsx
  ● Test suite failed to run

    ReferenceError: Request is not defined



      at new JsdomNodeEnvironment (tests/utils/jsdomNodeEnvironment.ts:24:31)

 FAIL  tests/services/FeatureFlagManager.test.ts
  ● Test suite failed to run

    ReferenceError: Request is not defined



      at new JsdomNodeEnvironment (tests/utils/jsdomNodeEnvironment.ts:24:31)


```

**Comment by mdragon** [comment]
No longer failing.
