### ISSUE TITLE
[Bug]: NPM install metadata fetch errors with 3 packages

### ISSUE THREAD

**Issue by doug-s-nava** [HHS/simpler-grants-gov#2195]
### Contact Details

dougschrashun@navapbc.com

### What happened?

When running an `npm install` on main, warnings about 3 packages appear:

* Could not fetch metadata for string-width-cjs@4.2.3 string-width-cjs: No matching version found for string-width-cjs@4.2.3.
* Could not fetch metadata for strip-ansi-cjs@6.0.1 strip-ansi-cjs: No matching version found for strip-ansi-cjs@6.0.1.
* Could not fetch metadata for wrap-ansi-cjs@7.0.0 wrap-ansi-cjs: No matching version found for wrap-ansi-cjs@7.0.0.

Have reproduced on npm 10.8.2 and 9.6.7

### Steps to reproduce the behavior

1. `npm install`
2. _VALIDATE_: errors appear in console as mentioned above

### Priority

low (inconvenience)

### Relevant log output

npm warn old lockfile Could not fetch metadata for string-width-cjs@4.2.3 string-width-cjs: No matching version found for string-width-cjs@4.2.3.
npm warn old lockfile     at module.exports (/Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:215:23)
npm warn old lockfile     at RegistryFetcher.manifest (/Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
npm warn old lockfile     at async /Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:712:24 {
npm warn old lockfile   code: 'ETARGET',
npm warn old lockfile   type: 'version',
npm warn old lockfile   wanted: '4.2.3',
npm warn old lockfile   versions: [ '1.0.0', '5.1.1' ],
npm warn old lockfile   distTags: { latest: '5.1.1' },
npm warn old lockfile   defaultTag: 'latest'
npm warn old lockfile }
npm warn old lockfile Could not fetch metadata for strip-ansi-cjs@6.0.1 strip-ansi-cjs: No matching version found for strip-ansi-cjs@6.0.1.
npm warn old lockfile     at module.exports (/Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:215:23)
npm warn old lockfile     at RegistryFetcher.manifest (/Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
npm warn old lockfile     at async /Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:712:24 {
npm warn old lockfile   code: 'ETARGET',
npm warn old lockfile   type: 'version',
npm warn old lockfile   wanted: '6.0.1',
npm warn old lockfile   versions: [ '1.0.0', '2.0.0', '8.0.0' ],
npm warn old lockfile   distTags: { latest: '8.0.0' },
npm warn old lockfile   defaultTag: 'latest'
npm warn old lockfile }
npm warn old lockfile Could not fetch metadata for wrap-ansi-cjs@7.0.0 wrap-ansi-cjs: No matching version found for wrap-ansi-cjs@7.0.0.
npm warn old lockfile     at module.exports (/Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:215:23)
npm warn old lockfile     at RegistryFetcher.manifest (/Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
npm warn old lockfile     at async /Users/dougschrashun/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:712:24 {
npm warn old lockfile   code: 'ETARGET',
npm warn old lockfile   type: 'version',
npm warn old lockfile   wanted: '7.0.0',
npm warn old lockfile   versions: [ '1.0.0', '8.0.0' ],
npm warn old lockfile   distTags: { latest: '8.0.0' },
npm warn old lockfile   defaultTag: 'latest'
npm warn old lockfile }

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MozamilS** [comment]
@doug-s-nava 

I was scrolling through the old bugs list and found this. 

At the moment, running `npm install` on project root directory results in the following: 

```
npm error code ENOENT
npm error syscall open
npm error path /Users/mozamilsadat/contributionProjects/simpler-grants-gov/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/mozamilsadat/contributionProjects/simpler-grants-gov/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /Users/mozamilsadat/.npm/_logs/2026-04-25T03_13_20_002Z-debug-0.log
```

**Comment by doug-s-nava** [comment]
@MozamilS I think the issue you're running into is that the `npm install` needs to be run from the `/frontend` directory. That's unrelated to this issue, which I can no longer reproduce, so I'll close it
