### ISSUE TITLE
Malformed markup in opportunity summary description causes front-end opportunity listing page to error

### ISSUE THREAD

**Issue by lucasmbrown-usds** [HHS/simpler-grants-gov#2776]
### Summary

For some opportunities, the front-end is giving 500 errors when trying to render the page. 

@chouinar believes this is because the opportunity summary description contains malformed HTML: 

> . On a hunch, I just copied one of them to my local DB and the local frontend now fails with:
> ⨯ Error: Malformed markup: improperly closed tag
>     at Array.from.reduce.preSplit (./src/utils/generalUtils.ts:36:23)
>     at Array.reduce (<anonymous>)
>     at splitMarkup (./src/utils/generalUtils.ts:20:62)
>     at SummaryDescriptionDisplay (./src/components/opportunity/OpportunityDescription.tsx:74:104)
>     at stringify (<anonymous>)
>     at stringify (<anonymous>)
> digest: "3520062763"
>   38 |       if (tracker.openTagIndicator && character === "/") {
>   39 |         if (tracker.closeTagIndicator) {
> > 40 |           throw new Error("Malformed markup: improperly closed tag");
>      |                 ^
>   41 |         }
>   42 |         tracker.closeTagIndicator = true;
>   43 |       }
>  ⨯ src/utils/generalUtils.ts (40:17) @ Array.from.reduce.preSplit
>  ⨯ Error: Malformed markup: improperly closed tag
>     at Array.from.reduce.preSplit (./src/utils/generalUtils.ts:36:23)
>     at Array.reduce (<anonymous>)
>     at splitMarkup (./src/utils/generalUtils.ts:20:62)
>     at SummaryDescriptionDisplay (./src/components/opportunity/OpportunityDescription.tsx:74:104)
>     at stringify (<anonymous>)
>     at stringify (<anonymous>)

We think this affects, at maximum, 20% of opportunity listings: from @chouinar again, "I’ve looked into it before as the frontend wanted to know how common HTML tags were. It was somewhere in the 10-20% range." Hopefully not all those listings contain malformed HTML.

It feels like, from poking around, it probably affects more like 2% of listings, maybe. We don't know yet. Google Analytics or New Relic might have more info.

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

1. Visit any of the following opportunity listings, which are all from USDA-FNS1:  

https://simpler.grants.gov/opportunity/356878
https://simpler.grants.gov/opportunity/356877
https://simpler.grants.gov/opportunity/356876
https://simpler.grants.gov/opportunity/309362 

2. Notice that the request to get the front-end page for that listing gives a 500 error, and the UI displays the following error: 

![Image](https://github.com/user-attachments/assets/de9ff241-2fa3-4f5b-bb0a-9e78f7c9eb0a)
 

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by widal001** [comment]
Beep boop: Automatically setting the point and sprint values for this issue in project HHS/13 because they were unset when the issue was closed.
